[data]
  email = "lloydjonesthomas@gmail.com"
  name = "DynamicApproach"

[data.git]
  email = "lloydjonesthomas@gmail.com"
  name = "DynamicApproach"

[template]
  include = [
    "{*,.*}",
    "!*.swp",
    "!*.bak",
    "!LICENSE",
    "!README.md",
    "!Makefile"
  ]
[run]
once = ["{{.chezmoi.sourceDir}}/scripts/run_once_setup_environment.sh"]