#!/bin/sh
# Directory where source configuration files are located
SRC_DIR=$(dirname "$0")
# Python installation function should be defined
install_python(){
    if command -v python3 &>/dev/null; then
        echo "Python 3 is installed"
    else
        echo "Python 3 is not installed, installing..."
        if [ "$(uname)" == "Darwin" ]; then
            brew install python
        elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
            sudo apt install python3 -y
        fi
    fi
}
case "$(uname)" in
    "Darwin")
        OS="macOS"
        UPDATE_COMMAND="brew update && brew upgrade"
        INSTALL_COMMAND="brew install"
        ;;
    "Linux")
        OS="Linux"
        UPDATE_COMMAND="sudo apt-get update && sudo apt-get upgrade -y"
        INSTALL_COMMAND="sudo apt-get install -y"
        ;;
    "MINGW32_NT"|"MINGW64_NT")
        OS="Windows"
        echo "Running on Windows"
        PS_SCRIPT_PATH="Windows/InstallChocolateyAndCreateProfile.ps1"
        if [ -f "$PS_SCRIPT_PATH" ]; then
            echo "Running PowerShell script"
            powershell.exe -ExecutionPolicy Bypass -File "$PS_SCRIPT_PATH"
        else
            echo "$PS_SCRIPT_PATH does not exist"
            exit 1
        fi
        ;;
    *)
        echo "Unsupported OS"
        exit 1
esac

echo "Detected $OS"
echo "Updating packages"
$UPDATE_COMMAND

# Install required packages
for package in zsh curl
do
    if ! command -v $package &> /dev/null
    then
        echo "$package not found, installing..."
        $INSTALL_COMMAND $package
    fi
done


install_python

if [ "$CODESPACES" != "true" ]; then
    echo "Changing default shell to Zsh"
    chsh -s $(which zsh)
else
    echo "In Codespaces, not changing default shell"
fi

if ! command -v starship &> /dev/null
then
    echo "Starship not found, installing..."
    curl -fsSL https://github.com/starship/starship/releases/latest/download/starship-x86_64-unknown-linux-musl.tar.gz | tar xvz -C /tmp
    sudo mv /tmp/starship /usr/local/bin/
fi



if ! grep -q 'eval "$(starship init zsh)"' ~/.zshrc
then
    echo 'eval "$(starship init zsh)"' >> ~/.zshrc
fi

echo "Moving configuration files"
for file in .zshrc .zsh_plugins.txt .gitconfig
do
    if [ ! -f $HOME/$file ]; then
        mv $SRC_DIR/$file $HOME/
    fi
done


if [ ! -f $HOME/.config/starship.toml ]; then
    mv $SRC_DIR/starship.toml $HOME/.config/starship.toml
fi

if [ "$(uname)" = "Darwin" ]; then
    sudo pip3 install wakatime
    if grep --quiet 'api_key=.' ~/.wakatime.cfg; then
        echo "WakaTime API-key already configured."
    else
        echo
        echo "Please input your secret API-key for WakaTime."
        echo "See https://wakatime.com/settings/api-key"
        read -p 'API-key: ' key
        echo -e "[settings]\napi_key=$key" >>~/.wakatime.cfg
    fi
    mkdir -p ~/.wakatime
    chmod 700 ~/.wakatime
fi

echo "Installation complete. Please close this terminal window and open a new one to see the changes."
